### ISSUE TITLE
运行时提示parse5模块不存在

### ISSUE THREAD

**Issue by amdgigabyte** [apache/incubator-weex-loader#11]
> gulp

module.js:339
    throw err;
    ^

Error: Cannot find module 'parse5'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/qiaofu/Sites/mtb/weex-pro/node_modules/weex-loader/lib/parser.js:12:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

**Comment by amdgigabyte** [comment]
0.3.0-alpha分支

**Comment by hirokith** [comment]
https://github.com/weexteam/weex-loader/pull/13

**Comment by Jinjiang** [comment]
Merged. NPM package will be published later.
Thanks
